driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.10
  - name: centos-6.5
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[rabbitmq::default]
  - name: cluster
    run_list:
      - recipe[rabbitmq::default]
    attributes:
      rabbitmq:
        cluster: true
        cluster_disk_nodes: ['rabbit@localhost']
  - name: lwrps
    run_list:
      - recipe[rabbitmq_test::lwrps]
